import ReactDOM from 'react-dom/client';
// import App from './01_类组件和函数式组件/App_class';
// import App from './01_类组件和函数式组件/App_func';
// import App from './02_组件生命周期函数/App';
// import App from './03_组件开发嵌套关系/App';
// import App from './04_组件通信-父传子/App';
// import App from './05_组件通信-子传父/App';
// import App from './06_组件通信案例练习/App';
// import App from './07_组件的插槽实现/App';
// import App from './08_组件的作用域插槽/App';
// import App from './09_非父子组件通信-Context/App';
// import App from './10_非父子组件通信-事件总线/App';
// import App from './11_setState详细使用/01_setState的三种写法';
// import App from './11_setState详细使用/App';
// import App from './12_render函数的优化/App';
// import App from './13_数据不可变/App';
// import App from './14_ref获取DOM操作/App';
import App from './15_受控和非受控组件/App';
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />)